version: '3.9'

services:
  leave-api:
    container_name: leave-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/LeaveManagementSystem.db
    volumes:
      - leave-db:/app/data
    restart: always

volumes:
  leave-db: